package fri.emp.odmevko

object SQL_PLAYLIST_TABLE {
    const val playlist = "CREATE TABLE PLAYLIST(ID INTEGER PRIMARY KEY AUTOINCREMENT, SONGTITLE TEXT DEFAULT '',  SONGARTIST TEXT DEFAULT '', SONGALBUM TEXT DEFAULT '', SONGIMAGE TEXT DEFAULT '', PLAY TEXT DEFAULT '')"
}